version: 2.1

orbs:
  python: circleci/python@1.3.1
  heroku: circleci/heroku@1.0.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: .
      - heroku/install
      - heroku/deploy:
          app-name: Unplugged
          code-path: .
          setup-file-path: setup.py
          environment: production
          requires-predeploy: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
